# Generated by Django 6.0.7 on 2026-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcels',
            name='Tracking_number',
            field=models.CharField(default='F89K35BD', max_length=15),
        ),
    ]
