# Generated by Django 6.0.7 on 2026-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_parcels_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='Tracking_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
