# Generated by Django 6.0.7 on 2026-07-21 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_parcels_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcels',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
