# Generated by Django 6.0.7 on 2026-08-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_user_confirm_password_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracking_number_user',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
