# Generated by Django 6.0.7 on 2026-07-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_parcels_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='parcels',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='parcels',
            old_name='Tracking_number',
            new_name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='parcels',
            name='surname',
        ),
        migrations.AddField(
            model_name='parcels',
            name='description',
            field=models.TextField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
