# Generated by Django 6.0.7 on 2026-08-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
