# Generated by Django 6.0.7 on 2026-08-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_user_name_remove_user_surname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcels',
            options={'permissions': [('can_view_parcels', 'Can view parcels'), ('can_edit_parcels', 'Can edit parcels'), ('can_delete_parcels', 'Can delete parcels')]},
        ),
    ]
